# Generated by Django 4.1.1 on 2024-08-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('url', models.SlugField(blank=True, max_length=15, null=True, verbose_name='Url de usuario')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Promedio del alumno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('url', models.SlugField(blank=True, max_length=15, null=True, verbose_name='Url de usuario')),
                ('experience', models.IntegerField(verbose_name='Años de experiencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Titulo del curso')),
                ('qualification', models.IntegerField(blank=True, default=8, null=True, verbose_name='Calificación')),
                ('img', models.ImageField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png', null=True, upload_to='', verbose_name='Imagen de fondo')),
                ('modules', models.IntegerField(blank=True, default=5, null=True, verbose_name='Cantidad de modulos')),
                ('description', models.TextField(blank=True, default='A good course', null=True, verbose_name='Descripcción')),
                ('price', models.IntegerField(blank=True, default=400, null=True, verbose_name='Precio del curso')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coursera.teacher', verbose_name='Profesor del curso')),
            ],
        ),
    ]
