# Generated by Django 4.2 on 2023-11-18 03:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0002_course_price_alter_course_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(90)])),
                ('experience', models.PositiveIntegerField()),
                ('courses', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coursera.teacher'),
        ),
    ]
