# Generated by Django 4.2 on 2023-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0003_teacher_rename_name_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='Django.jpg', upload_to=''),
        ),
    ]
