# Generated by Django 4.2 on 2023-11-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0004_alter_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='A good course to learning this technology'),
        ),
    ]
