# Generated by Django 4.2 on 2023-11-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0005_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=30),
        ),
    ]
