# Generated by Django 4.2 on 2023-11-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0006_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='https://assets-global.website-files.com/6410ebf8e483b5bb2c86eb27/6410ebf8e483b53d6186fc53_ABM%20College%20Web%20developer%20main.jpg', upload_to=''),
        ),
    ]
