# Generated by Django 4.2 on 2023-11-22 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0008_alter_course_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='qualification',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
