# Generated by Django 4.2.7 on 2023-12-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0012_alter_course_qualification_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
