# Generated by Django 4.2.7 on 2023-12-09 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0013_course_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='qualification',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
