# Generated by Django 4.2.7 on 2023-12-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0015_alter_course_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(choices=[('opt 1', 'Álvaro Felipe'), ('opt 2', 'Beto Quiroga'), ('opt 3', 'Alexys Lozada'), ('opt 4', 'Johnny'), ('opt 5', 'Queta Rodriguez'), ('opt 6', 'Oscar Alzada')], default='Álvaro Felipe', max_length=30),
        ),
    ]
