# Generated by Django 4.2.7 on 2024-01-16 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0016_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='qualification',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
