# Generated by Django 4.2.7 on 2024-01-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0017_alter_course_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
