# Generated by Django 4.2.7 on 2024-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0021_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='date',
        ),
    ]
