# Generated by Django 4.2.7 on 2024-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0022_remove_vehicle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
