# Generated by Django 4.2.7 on 2024-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0023_alumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumn',
            name='url',
            field=models.CharField(default='https://', max_length=40),
        ),
    ]
