# Generated by Django 4.1.1 on 2024-05-13 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Coursera', '0024_alumn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumn',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumn',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
