# Generated by Django 4.1.1 on 2024-08-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nombre')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('url', models.SlugField(blank=True, max_length=15, null=True, verbose_name='Url de usuario')),
                ('background', models.TextField(default='Contenido publico', verbose_name='De que tratará tu canal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, unique=True, verbose_name='Titulo')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='Nuevo contenido', null=True, verbose_name='Descripcción')),
                ('img', models.ImageField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/2048px-Python.svg.png', null=True, upload_to='', verbose_name='Imagen de fondo')),
                ('views', models.IntegerField(blank=True, null=True)),
                ('youtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouTube.youtuber', verbose_name='Youtuber')),
            ],
        ),
    ]
