# Generated by Django 4.2.7 on 2024-01-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('during', models.IntegerField(default=5)),
                ('description', models.CharField(default='Enjoy the content from this tube ;)!.', max_length=200)),
            ],
        ),
    ]
