# Generated by Django 4.2.7 on 2024-01-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default='https://i.blogs.es/9b19ad/youtube/1366_2000.jpg', upload_to=''),
        ),
    ]
