# Generated by Django 4.2 on 2024-02-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0003_video_icon_video_views_video_youtuber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=15)),
                ('img', models.ImageField(default='https://images.justwatch.com/poster/261483319/s718/boku-no-hero-academy.jpg', upload_to='')),
                ('description', models.TextField()),
                ('seasons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('topyc', models.CharField(max_length=100)),
            ],
        ),
    ]
