# Generated by Django 4.2 on 2024-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0005_alter_video_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtuber',
            field=models.ForeignKey(default='Johnny', on_delete=django.db.models.deletion.CASCADE, to='YouTube.youtuber'),
        ),
    ]
