# Generated by Django 4.2 on 2024-02-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0006_alter_video_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtuber',
            field=models.CharField(default='Developer avenger', max_length=70),
        ),
    ]
