# Generated by Django 4.2 on 2024-02-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0007_alter_video_youtuber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtuber',
        ),
    ]
