# Generated by Django 4.2 on 2024-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0008_remove_video_youtuber'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtuber',
            field=models.CharField(default='Developer avenger', max_length=70),
        ),
    ]
