# Generated by Django 4.2.7 on 2024-03-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTube', '0009_video_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(default='https://images.justwatch.com/poster/261483319/s718/boku-no-hero-academy.jpg', upload_to=''),
        ),
    ]
